[package]
name = "trade-generator"
version = "0.2.0"
edition = "2021"

[lib]
name = "fx_trade_gen"
path = "src/lib.rs"

[[bin]]
name = "fx_trade_gen"
path = "src/bin/main.rs"

[dependencies]
rand = "0.8.5"